<?php
/**
 * Copyright © 2016 Magevolve Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying Products by Quantity Range widget
 *
 * @var $block \Me\Aos\Block\Catalog\Product\Widget\AosWidget
 */
$title = $block->getTitle();
$subtitle = $block->getSubTitle();
?>
<?php if ($block->getExtensionHelper()->isEnabled()
    && ($_products = $block->getProductsCollection())
    && $_products->getSize()) : ?>
    <?php $outputHelper = $this->helper('Magento\Catalog\Helper\Output'); ?>
    <div class="block widget block-aos-products-names">
        <?php if ($block->getShowTitle()) : ?>
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo $block->escapeHtml($title) ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <?php if ($subtitle != '') : ?>
                <p class="block-subtitle"><?php /* @noEscape */ echo $subtitle ?></p>
            <?php endif; ?>
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-aos-products-<?php /* @noEscape */ echo $suffix; ?>"
                class="product-items product-items-names">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_products->getItems() as $_product) : ?>
                    <?php $name = $outputHelper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    <?php $productName = $block->stripTags($_product->getName(), null, true); ?>
                    <li class="product-item">
                        <strong class="product-item-name">
                            <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                               title="<?php /* @noEscape */ echo $block->stripTags($productName) ?>)"
                               class="product-item-link">
                                <?php /* @noEscape */ echo $name ?>
                            </a>
                        </strong>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
