<?php
/**
 * Copyright © 2016 Magevolve Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying Products by Quantity Range widget
 *
 * @var $block \Me\Aos\Block\Catalog\Product\Widget\AosWidget
 */
$title = $block->getTitle();
$subtitle = $block->getSubTitle();
?>
<?php if ($block->getExtensionHelper()->isEnabled()
    && ($_products = $block->getProductsCollection())
    && $_products->getSize()) : ?>
<div class="block widget block-aos-products-list">
    <?php if ($block->getShowTitle()) : ?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */echo $block->escapeHtml($title) ?></strong>
        </div>
    <?php endif; ?>
    <div class="block-content">
        <?php if ($subtitle != '') : ?>
            <p class="block-subtitle"><?php /* @noEscape */ echo $subtitle ?></p>
        <?php endif; ?>
        <?php $suffix = $block->getNameInLayout(); ?>
        <?php $itr = 1; ?>
        <ol class="product-items"
            id="widget-aos-products-<?php /* @noEscape */ echo $suffix; ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_products->getItems() as $_product) : ?>
                <?php
                    $productTitle = $block->stripTags($_product->getName(), null, true);
                    $cartUrl = $block->getAddToCartUrl($_product);
                ?>
                <?php
                    /* @noEscape */ echo($itr++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">'
                ?>
                <div class="product-item-info">
                    <a class="product-item-photo" href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                       title="<?php /* @noEscape */ echo $block->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $block->getImage($_product, 'side_column_widget_product_thumbnail')->toHtml(); ?>
                    </a>
                    <div class="product-item-details">
                        <strong class="product-item-name">
                            <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                               title="<?php /* @noEscape */ echo $productTitle ?>)"
                               class="product-item-link">
                                <?php /* @noEscape */ echo $this->helper('Magento\Catalog\Helper\Output')
                                    ->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?php
                            /* @noEscape */ echo $block->getProductPriceHtml($_product, '-widget-aos-' . $suffix)
                        ?>
                        <div class="product-item-actions">
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()) : ?>
                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)) : ?>
                                        <button type="button"
                                                title="<?php /* @noEscape */ echo __('Add to Cart') ?>"
                                                class="action tocart primary"
                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @noEscape */ echo $cartUrl ?>"}}'>
                                            <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php else : ?>
                                        <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData(
                                                $block->getAddToCartUrl($_product),
                                                ['product' => $_product->getEntityId()]
                                            );
                                        ?>
                                        <button type="button"
                                                title="<?php /* @noEscape */ echo __('Add to Cart') ?>"
                                                class="action tocart primary"
                                                data-post='<?php /* @noEscape */ echo $postData; ?>'>
                                            <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <?php if ($_product->getIsSalable()) : ?>
                                        <div class="stock available"
                                             title="<?php /* @noEscape */ echo __('Availability') ?>">
                                            <span><?php /* @noEscape */ echo __('In stock') ?></span>
                                        </div>
                                    <?php else : ?>
                                        <div class="stock unavailable"
                                             title="<?php /* @noEscape */ echo __('Availability') ?>">
                                            <span><?php /* @noEscape */ echo __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($itr == count($_products->getItems())+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <?php echo $block->getPagerHtml() ?>
    </div>
</div>
<?php endif; ?>
