<?php
/**
 * Copyright © 2016 Magevolve Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->getExtensionHelper()->isEnabled()) : ?>
    <?php
    /**
     * Template for displaying Products by Quantity Range widget
     *
     * @var $block \Me\Aos\Block\Catalog\Product\Widget\AosWidget
     */
    if ($exist = ($block->getProductsCollection() && $block->getProductsCollection()->getSize())) {
        $type = 'widget-aos-list';

        $mode = 'list';

        $image = 'aos_products_content_widget_list';
        $title = $block->getTitle();
        $subtitle = $block->getSubTitle();
        $items = $block->getProductsCollection()->getItems();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');

        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
        $description = true;
    }
    ?>

    <?php if ($exist) : ?>
        <div class="block widget block-aos-products <?php /* @noEscape */ echo $mode; ?>">
            <?php if ($block->getShowTitle()) : ?>
                <div class="block-title">
                    <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $block->escapeHtml($title); ?></strong>
                </div>
            <?php endif; ?>
            <div class="block-content">
                <?php if ($subtitle != '') : ?>
                    <p class="subtitle"><?php /* @noEscape */ echo $subtitle ?></p>
                <?php endif; ?>
                <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php /* @noEscape */ echo $mode; ?> <?php /* @noEscape */ echo $mode; ?>">
                    <ol class="product-items <?php /* @noEscape */ echo $type; ?>">
                        <?php $itr = 1; ?>
                        <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($items as $_item) : ?>
                            <?php /* @noEscape */ echo($itr++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info">
                                <a href="<?php /* @noEscape */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php /* @noEscape */ echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?php /* @escapeNotVerified */ echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @noEscape */ echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>

                                    <?php if ($templateType) : ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()) : ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @noEscape */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                                <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?php /* @noEscape */ echo $postData; ?>'
                                                                    type="button" title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                                <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else : ?>
                                                        <?php if ($_item->getIsSalable()) : ?>
                                                            <div class="stock available"><span><?php /* @noEscape */ echo __('In stock') ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?php /* @noEscape */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare) : ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) : ?>
                                                        <a href="#"
                                                           data-post='<?php /* @noEscape */ echo $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php /* @noEscape */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @noEscape */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                        <a href="#" class="action tocompare"
                                                           title="<?php /* @noEscape */ echo __('Add to Compare') ?>"
                                                           data-post='<?php /* @noEscape */ echo $compareHelper->getPostDataParams($_item);?>'>
                                                            <span><?php /* @noEscape */ echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($description) :?>
                                        <div class="product-item-description">
                                            <?php /* @noEscape */ echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @noEscape */ echo $block->getProductUrl($_item) ?>"
                                               class="action more"><?php /* @noEscape */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($itr == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    <?php endif;?>
<?php endif; ?>